### ISSUE TITLE
Missing asset folder in step-05

### ISSUE THREAD

**Issue by 0rland0** [learnrelay/pokedex#1]
There is no asset folder with the delete.svg icon so the PokemonPage can't load as it does not find the delete image in line 5 in PokemonPage.js

`import deleteIcon from '../assets/delete.svg'`

**Comment by renebrandel** [comment]
This is fixed by #2 and #3 
Thanks @0rland0

**Comment by schickling** [comment]
Please close this as soon as it's merged to master.
