### ISSUE TITLE
ESLint'ing Errors

### ISSUE THREAD

**Issue by idkjs** [learnrelay/pokedex#12]
I did a git checkout on this file, ran npm start and got the following linting errors. Noting in case this isn't expected given the there is an '.eslintrc file in the repo. 
![learnrelay3](https://cloud.githubusercontent.com/assets/2370391/18753448/a09e0824-80e5-11e6-89da-f4804887f379.PNG)

**Comment by marktani** [comment]
On which branch did this happen?

**Comment by idkjs** [comment]
Step-02 Solution. Actually happened on Step-02 as well so I went to check out the solution to see if I did something in Step-02. Got the same result in both cases.

**Comment by lvarayut** [comment]
@aarmand, the errors were fixed by 7e0222bc27aa40bbd0a253274a6ef082f1640fed, could you pull the latest commit and try again?

**Comment by marktani** [comment]
@lvarayut make sure to run the update script after making commits on the `master` branch, I updated it now :+1:
