### ISSUE TITLE
(feature request) Create a standalone express graphql server

### ISSUE THREAD

**Issue by lowsky** [learnrelay/pokedex#15]
There are some examples for how to setup a simple graphql server, e.g.

https://medium.com/apollo-stack/tutorial-building-a-graphql-server-cddaa023c035

We could implement a simple version with just the needed features for Pokedex.

**Comment by schickling** [comment]
Hey @lowsky. Thanks for your request! One of the goals of Learn Relay is to purely focussing on the frontend and not distracting with the development/setup of a GraphQL backend.

You're more than welcome to create a "matching" GraphQL backend. If it's seamless enough I think it would also be nice to link to it at the end of the guide.
