### ISSUE TITLE
Wrong link in README.md

### ISSUE THREAD

**Issue by bjornarg** [learnrelay/pokedex#27]
The link in `If you haven't done it already, checkout the interactive Learn Relay tutorial.` in README.md links to `https://learnrelay.org/` which redirects to `https://www.learnrelay.com/`, which does not exist. Should probably link to `https://www.learnrelay.org/`, and `https://learnrelay.org/` should not redirect to `.com`, but `.org`.

**Comment by marktani** [comment]
Thanks for the heads up!
