### ISSUE TITLE
[Meta] Improve contribution workflow

### ISSUE THREAD

**Issue by marktani** [learnrelay/pokedex#7]
Our current workflow goes like this:

> Changes to the separate steps should be made in the respective folder in the `master` branch. After all changes, the `update-branches.sh` script should be executed that syncs these folders with the separate branches.

This is an issue when contributors create a pull request for a separate branch, as the `master` branch falls out of sync. Also, when the PR is merged but afterwards the `update-branches.sh` script is executed, the commits on the branch are lost.

The following things have to be done:
- fix the inconsistencies brought up by PR #6, its merging and the force push done by `update-branches.sh`
- fix other inconsistent branches. these include at least `step-01`, `step-01-solution` and `step-05`
- find a workflow for PRs that works for contributors and doesn't introduce inconsistencies. create CONTRIBUTE.md that communicates clearly how to contribute.

A suggestion for a PR workflow:
- Add the separate folders to `.gitignore` in `master`
- introduce `pull-branches.sh` that pulls all branches into separate folders to the `master` branch 

Then a possible workflow could look like this

> go to the `master` branch. execute `pull-branches.sh`. introduce changes to a branch in its folder. call `update-branches.sh` to sync the changes from the folder to the branch.

**Comment by schickling** [comment]
What's the downside of _just_ working on the `master` branch and discouraging people from doing PRs for the generated branches?

**Comment by renebrandel** [comment]
Because people will change everything and then in the end, when they actually want to commit it, they'll realize that they should work on the master branch. This could decrease the motivation of creating pull requests.

**Comment by schickling** [comment]
I think this is rather a matter of clear communication. I worry that introducing a `pull-branches.sh` opens a whole new level of potential problems. But I'm open to try it 👍

**Comment by renebrandel** [comment]
What problems do you see in `pull-branches.sh`?

**Comment by schickling** [comment]
Two-way merging is way more complicated and error prone than a unidirectional workflow.

**Comment by ram535ii** [comment]
I think @brene makes a good point. I definitely contributed straight to one of the branches, but there is no `CONTRIBUTE.md` yet. 

On the other hand, I think @schickling is onto something with keeping the git flow as simple as possible. 

As such, would it make sense to stick with what we've got and at least try a `CONTRIBUTE.md`? (and be SUPER explicit) At least for the moment I imagine %99 of all PRs coming internally and as such keeping it simple will speed things up.

**Comment by schickling** [comment]
Agree! Do you guys quickly want to draft a `CONTRIBUTE.md`?

**Comment by marktani** [comment]
Done :)

**Comment by marktani** [comment]
I still think the first two bullet points have to be adressed
- fix the inconsistencies brought up by PR #6, its merging and the force push done by update-branches.sh
- fix other inconsistent branches. these include at least step-01, step-01-solution and step-05

@brene, can you help me out here?
